### PR TITLE
fix: Allow for windows style paths

### LINKED ISSUE #133: Wrong path to images.
I use configuration like in the documentation.
The problem is that images doesn't appear in html-reporter see attached picture.
I'm running `gemini gui`

```
module.exports = {
    // ...
    system: {
        plugins: {
            'html-reporter/gemini': {
                enabled: true,
                path: 'my/gemini-reports',
                defaultView: 'all',
                baseHost: 'test.com'
            }
        }
    },
    //...
}
```
gui report - google chrome 2018-07-11 18 33 59

### PR DESCRIPTION
**Pull request by jacobwindsor**
Adds a new normalizeToPosixPath utility function that is used in all areas where paths are resolved..

Fixes #133

### CODE REVIEW

**Comment by Kreozot** [comment]
It brokes the gui

Error: ENOENT: no such file or directory, stat 'd:\repo\realty_front\node_modules\html-reporter\lib\static\gui.html'

**Comment by DudaGod** [comment]
@Kreozot are your sure that you run `npm run prepublish`?

@jacobwindsor can you please write tests?

**Comment by Kreozot** [comment]
Oh, maybe it is my fault. I've installed the package from repository. Later I'll try to prepublish.14:05, 12 ноября 2018 г., Dmitriy Dudkevich <notifications@github.com>:@Kreozot are your sure that you run npm run prepublish?
@jacobwindsor can you please write tests?

—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or mute the thread.

-- Отправлено из мобильного приложения Яндекс.Почты

**Comment by Kreozot** [comment]
Ok. I installed it properly and no only first run is working (until you don't clear report directory)

```
d:\repo\myproj>npx gemini update
✓ components plain [chrome]
Total: 1 Updated: 1 Passed: 0 Failed: 0 Skipped: 0 Retries: 0
Your HTML report is here: file://d:\repo\myproj\gemini\report\index.html

d:\repo\myproj>npx gemini update
Critical error:
ReferenceError: window is not defined
    at Object.<anonymous> (d:\repo\myproj\gemini\report\report.min.js:39:59095)
    at t (d:\repo\myproj\gemini\report\report.min.js:1:163)
    at Object.<anonymous> (d:\repo\myproj\gemini\report\report.min.js:39:44716)
    at t (d:\repo\myproj\gemini\report\report.min.js:1:163)
    at Object.<anonymous> (d:\repo\myproj\gemini\report\report.min.js:54:77094)
    at t (d:\repo\myproj\gemini\report\report.min.js:1:163)
    at Object.<anonymous> (d:\repo\myproj\gemini\report\report.min.js:54:76947)
    at t (d:\repo\myproj\gemini\report\report.min.js:1:163)
    at d:\repo\myproj\gemini\report\report.min.js:1:513
    at Object.<anonymous> (d:\repo\myproj\gemini\report\report.min.js:1:524)
    at Module._compile (internal/modules/cjs/loader.js:702:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:713:10)
    at Module.load (internal/modules/cjs/loader.js:612:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:551:12)
    at Function.Module._load (internal/modules/cjs/loader.js:543:3)
    at Module.require (internal/modules/cjs/loader.js:650:17)
```

**Comment by jacobwindsor** [comment]
@DudaGod I'm not sure how to test it since it's a windows/unix thing. I can't emulate a different environment. I will write a unit test for the util function I added though.

**Comment by DudaGod** [comment]
We have already fixed it - https://github.com/gemini-testing/html-reporter/pull/316.
Fix is available in - html-reporter@5.15.3.

**Pull request closed without merging**
