### PR TITLE
Fixes for Windows

### LINKED ISSUE #27: chrome and %5С
Добрый день! Не отображаются скриншоты в отчёте в браузере chrome: в url обратный слеш заменяется на %5C.
html-report

p.s.: корректно работает только в firefox.

### PR DESCRIPTION
**Pull request by generalov**
The PR is about running html-reporter on Windows.

Fixes #27

### CODE REVIEW

**Comment by haulin** [comment]
This fixes the issue, and produces src attributes that load fine on Chrome on Windows. However at the end of "gemini test" it errors when trying to log the report path:
```ENOENT: no such file or directory, lstat 'node_modules\html-reporter\lib\static\report.min.js'
TypeError: Cannot read property 'reportPath' of undefined
    at logPathToHtmlReport (node_modules\html-reporter\lib\server-utils.js:79:48)
    at tryCatcher (node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (node_modules\bluebird\js\release\promise.js:512:31)
    at Promise._settlePromise (node_modules\bluebird\js\release\promise.js:569:18)
    at Promise._settlePromise0 (node_modules\bluebird\js\release\promise.js:614:10)
    at Promise._settlePromises (node_modules\bluebird\js\release\promise.js:693:18)
    at Promise._fulfill (node_modules\bluebird\js\release\promise.js:638:18)
    at Promise._resolveCallback (node_modules\bluebird\js\release\promise.js:432:57)
    at Promise._settlePromiseFromHandler (node_modules\bluebird\js\release\promise.js:524:17)
    at Promise._settlePromise (node_modules\bluebird\js\release\promise.js:569:18)
    at Promise._settlePromise0 (node_modules\bluebird\js\release\promise.js:614:10)
    at Promise._settlePromises (node_modules\bluebird\js\release\promise.js:689:18)
    at Async._drainQueue (node_modules\bluebird\js\release\async.js:133:16)
    at Async._drainQueues (node_modules\bluebird\js\release\async.js:143:10)
    at Immediate.Async.drainQueues (node_modules\bluebird\js\release\async.js:17:14)
    at runCallback (timers.js:810:20)```

**Comment by generalov** [comment]
Hi @haulin,
Thanks for feedback. Suddenly it's tricky to determinate root cause of the issue from the stack trace. `.catch()` at the https://github.com/gemini-testing/html-reporter/blob/master/lib/report-builder-factory/report-builder.js#L159 hides actual error. Could you please remove the line and run `gemini test` one more time?

**Comment by haulin** [comment]
Hi @generalov , thanks for getting back to me. I did that and now it says `Error: ENOENT: no such file or directory, lstat 'node_modules\html-reporter\lib\static\index.html'`. When I npm install the original html-reporter from gemini-testing it gets generated there, but it's not committed to the [original repo](https://github.com/gemini-testing/html-reporter/tree/master/lib/static). What sorcery is this? :D Maybe you just need to bring this branch up to date?

**Comment by generalov** [comment]
@haulin There is [prepublish script](https://github.com/gemini-testing/html-reporter/blob/master/package.json#L10) in package.json that builds the files. The files are not included in git repository. You need to build them manually if you want to use the plugin from sources.

**Comment by haulin** [comment]
Sorry I don't get that. Do I need to run `npm run prepublish` manually if I use a specific branch? You know in my package.json I only changed `"html-reporter": "^2.17.1",` for `"html-reporter": "generalov/html-reporter#808b8928b32d",`. I don't understand why the prepublish script doesn't run now.

I see you changed that script to run cross-env. Is that supposed to create a .bin executable in my project's node_modules? Because that isn't happening... :confused:

**Comment by stevegibbings** [comment]
@haulin run `npm install` in this packages folder:-)

**Comment by stevegibbings** [comment]
@generalov Thanks for doing the PR. I'm working with @haulin.

When I install I am getting a webpack error,

```ERROR in ./gui.js
Module parse failed: Unexpected token (12:4)
You may need an appropriate loader to handle this file type.
| 
| ReactDOM.render(
|     <Provider store={store}>
|         <Gui/>
|     </Provider>,
 @ multi ./gui.js ./styles.css ./gui.css

ERROR in ./index.js
Module parse failed: Unexpected token (12:4)
You may need an appropriate loader to handle this file type.
| 
| ReactDOM.render(
|     <Provider store={store}>
|         <Report/>
|     </Provider>,
 @ multi ./index.js ./styles.css```

Missing loader?

**Comment by stevegibbings** [comment]
So I tried reverting to the version in the npm registry and running `npm install` on that version, it fails in the same way. Am I trying to do this in the wrong way?

**Comment by jacobwindsor** [comment]
Woops, I've fixed this same issue in a slightly different way in #152 

Feel free to close mine without merging if you like.

**Comment by generalov** [comment]
Thanks a lot. Closed.

**Pull request closed without merging**
